/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.ifpr.biblioteca.view;

import br.ifpr.biblioteca.dao.AlunoDaoImpl;
import br.ifpr.biblioteca.dao.ArmarioDaoImpl;
import br.ifpr.biblioteca.dao.PessoaDaoImpl;
import br.ifpr.biblioteca.modelo.Aluno;
import br.ifpr.biblioteca.modelo.Armario;
import br.ifpr.biblioteca.modelo.Pessoa;
import javax.swing.JOptionPane;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Random;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author pedro
 */
public class InsercaoAluno extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form TelaReserva
     */
    
    
    public InsercaoAluno() {
        initComponents();
        
        atualizarTabelaView();
        
    }
    
    public boolean AbreTelaReserva(){
        this.setVisible(true);
        return true;
    }
    
    public boolean FechaTelaReserva(){
        this.setVisible(false);
        return false;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaArmario = new javax.swing.JTable();
        lNome = new javax.swing.JTextField();
        lCPF = new javax.swing.JTextField();
        lEmail = new javax.swing.JTextField();
        lTelefone = new javax.swing.JTextField();
        bConsultar = new javax.swing.JButton();
        lRA = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        lCodigo = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        TabelaArmario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaArmario.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(TabelaArmario);

        lNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        lNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNomeActionPerformed(evt);
            }
        });

        lCPF.setToolTipText("");
        lCPF.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        lCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lCPFActionPerformed(evt);
            }
        });

        lEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        lEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lEmailActionPerformed(evt);
            }
        });

        lTelefone.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));

        bConsultar.setText("Consultar");
        bConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarActionPerformed(evt);
            }
        });

        lRA.setBorder(javax.swing.BorderFactory.createTitledBorder("RA"));
        lRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lRAActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        lCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(bConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(124, 124, 124)
                        .addComponent(Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lRA, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lCPF))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                        .addComponent(lEmail)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lNome)
                            .addGap(18, 18, 18)
                            .addComponent(lTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alterar)
                    .addComponent(bConsultar)
                    .addComponent(Cadastrar)
                    .addComponent(Excluir))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        Integer novoId = Integer.parseInt(lCodigo.getText());
        String novoNome = lNome.getText();
        String novoCPF = lCPF.getText();
        String novoEmail = lEmail.getText();
        String novoTelefone = lTelefone.getText();
        boolean status = true;
        

        Aluno aluno = new Aluno(
            novoNome,novoCPF,novoEmail,novoTelefone,
            lRA.getText()

        );
        
        AlunoDaoImpl daoAluno = new AlunoDaoImpl();

        daoAluno.inserir(aluno);

        JOptionPane.showMessageDialog(null, "Aluno "+ lNome.getText()+" alterado com sucesso!");
        
        atualizarTabelaView();
    }//GEN-LAST:event_CadastrarActionPerformed

    private void bConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarActionPerformed
        trazerCamposPessoa();
    }//GEN-LAST:event_bConsultarActionPerformed

    private void lEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lEmailActionPerformed

    private void lCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lCPFActionPerformed

    private void lNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNomeActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed

        int pessoaID = Integer.parseInt(lCodigo.getText());
        String novoNome = lNome.getText();
        String novoCPF = lCPF.getText();
        String novoEmail = lEmail.getText();
        String novoTelefone = lTelefone.getText();
        boolean status = true;
        

        Aluno aluno = new Aluno(
            pessoaID,novoNome,novoCPF,novoEmail,novoTelefone,status,
            lRA.getText()
        );
        
        AlunoDaoImpl daoAluno = new AlunoDaoImpl();

        daoAluno.excluir(aluno);

        JOptionPane.showMessageDialog(null, "Aluno "+ lNome.getText()+" exlcuido com sucesso!");
        
        atualizarTabelaView();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        
        int pessoaID = Integer.parseInt(lCodigo.getText());
        String novoNome = lNome.getText();
        String novoCPF = lCPF.getText();
        String novoEmail = lEmail.getText();
        String novoTelefone = lTelefone.getText();
        boolean status = true;
        

        Aluno aluno = new Aluno(
            pessoaID,novoNome,novoCPF,novoEmail,novoTelefone,status,
            lRA.getText()
        );
        
        AlunoDaoImpl daoAluno = new AlunoDaoImpl();

        daoAluno.atualizar(aluno);

        JOptionPane.showMessageDialog(null, "Aluno "+ lNome.getText()+" alterado com sucesso!");
        
        atualizarTabelaView();
    }//GEN-LAST:event_AlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void lRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lRAActionPerformed

    
    private void popularTabelaView(List<Aluno> listaAluno) {
        
        DefaultTableModel modeloTabela = new DefaultTableModel();
        
        this.TabelaArmario.setModel(modeloTabela);
      
        modeloTabela.addColumn("ID");
        modeloTabela.addColumn("Nome");
        modeloTabela.addColumn("Email");
        modeloTabela.addColumn("Telefone");
        modeloTabela.addColumn("CPF");
        modeloTabela.addColumn("RA");
        modeloTabela.addColumn("Ativo");
        
        for(Aluno aluno: listaAluno) {
            modeloTabela.addRow(
                    new Object[]{
                        aluno.getPessoaID(),
                        aluno.getNome(),
                        aluno.getEmail(),
                        aluno.getTelefone(),
                        aluno.getCPF(),
                        aluno.getRA(),
                        aluno.getAtivo()
                }
            );
        }
      
    }
    
    private void atualizarTabelaView() {
        AlunoDaoImpl dao = new AlunoDaoImpl();
        
        List<Aluno> listaAluno = new ArrayList();
        
        listaAluno = dao.buscarTodos();
        
        this.popularTabelaView(listaAluno);
    }
    
    private void trazerCamposPessoa() {
        
        AlunoDaoImpl daoAluno = new AlunoDaoImpl();  
        
        int idPessoa = Integer.parseInt(lCodigo.getText());
        
        PessoaDaoImpl daoPessoa = new PessoaDaoImpl();
        
        Pessoa pessoa = new Pessoa();
        
        lNome.setText(daoPessoa.buscarPorId(idPessoa).getNome());
        lCPF.setText(daoPessoa.buscarPorId(idPessoa).getCPF());
        lEmail.setText(daoPessoa.buscarPorId(idPessoa).getEmail());
        lTelefone.setText(daoPessoa.buscarPorId(idPessoa).getTelefone());
        lRA.setText(daoAluno.buscarPorId(idPessoa).getRA());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Excluir;
    private javax.swing.JTable TabelaArmario;
    private javax.swing.JButton bConsultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lCPF;
    private javax.swing.JTextField lCodigo;
    private javax.swing.JTextField lEmail;
    private javax.swing.JTextField lNome;
    private javax.swing.JTextField lRA;
    private javax.swing.JTextField lTelefone;
    // End of variables declaration//GEN-END:variables
}
