/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifpr.biblioteca.view;

import static java.awt.SystemColor.desktop;

/**
 *
 * @author Aluno
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        armarioDados = new javax.swing.JMenu();
        InserirArmario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ConsultarArmario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        armarioDados1 = new javax.swing.JMenu();
        InserirAluno = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        ConsultarArmario1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        armarioDados.setText("Armarios");

        InserirArmario.setText("Inserir/Alterar/Exlcuir");
        InserirArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirArmarioActionPerformed(evt);
            }
        });
        armarioDados.add(InserirArmario);
        armarioDados.add(jSeparator2);

        ConsultarArmario.setText("Consultar");
        ConsultarArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarArmarioActionPerformed(evt);
            }
        });
        armarioDados.add(ConsultarArmario);

        jMenuItem1.setText("Consulta por Id");
        armarioDados.add(jMenuItem1);

        jMenuBar1.add(armarioDados);

        armarioDados1.setText("Alunos");

        InserirAluno.setText("Cadastrar/Alterar/Excluir");
        InserirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirAlunoActionPerformed(evt);
            }
        });
        armarioDados1.add(InserirAluno);
        armarioDados1.add(jSeparator3);

        ConsultarArmario1.setText("Consultar");
        ConsultarArmario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarArmario1ActionPerformed(evt);
            }
        });
        armarioDados1.add(ConsultarArmario1);

        jMenuItem2.setText("Consulta por Id");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        armarioDados1.add(jMenuItem2);

        jMenuBar1.add(armarioDados1);

        jMenu1.setText("Reserva");

        jMenuItem3.setText("Reservar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarArmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarArmarioActionPerformed

    private void InserirArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirArmarioActionPerformed
        InsercaoArmario ia = new InsercaoArmario();
        jDesktopPane1.add(ia);
        ia.setVisible(true);
        
    }//GEN-LAST:event_InserirArmarioActionPerformed

    private void InserirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirAlunoActionPerformed
        InsercaoAluno ia = new InsercaoAluno();
        jDesktopPane1.add(ia);
        ia.setVisible(true);
    }//GEN-LAST:event_InserirAlunoActionPerformed

    private void ConsultarArmario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarArmario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarArmario1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaReserva tr = new TelaReserva();
        jDesktopPane1.add(tr);
        tr.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ViewAlunos va = new ViewAlunos();
        jDesktopPane1.add(va);
        va.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultarArmario;
    private javax.swing.JMenuItem ConsultarArmario1;
    private javax.swing.JMenuItem InserirAluno;
    private javax.swing.JMenuItem InserirArmario;
    private javax.swing.JMenu armarioDados;
    private javax.swing.JMenu armarioDados1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
