/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifpr.biblioteca.view;

/**
 *
 * @author Aluno
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        alunoDados = new javax.swing.JMenu();
        InserirAluno = new javax.swing.JMenuItem();
        AlterarAluno = new javax.swing.JMenuItem();
        ExcluirAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Consulta = new javax.swing.JMenu();
        ConsultaPorAluno = new javax.swing.JMenuItem();
        ConsultaGeral = new javax.swing.JMenuItem();
        armarioDados = new javax.swing.JMenu();
        InserirArmario = new javax.swing.JMenuItem();
        AlterarArmario = new javax.swing.JMenuItem();
        ExlcuirArmario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ConsultarArmario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        alunoDados.setText("Alunos");

        InserirAluno.setText("Inserir");
        InserirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirAlunoActionPerformed(evt);
            }
        });
        alunoDados.add(InserirAluno);

        AlterarAluno.setText("Alterar");
        AlterarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarAlunoActionPerformed(evt);
            }
        });
        alunoDados.add(AlterarAluno);

        ExcluirAluno.setText("Exlcuir");
        alunoDados.add(ExcluirAluno);
        alunoDados.add(jSeparator1);

        Consulta.setText("Consultar");

        ConsultaPorAluno.setText("Por Aluno");
        ConsultaPorAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPorAlunoActionPerformed(evt);
            }
        });
        Consulta.add(ConsultaPorAluno);

        ConsultaGeral.setText("Geral");
        ConsultaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaGeralActionPerformed(evt);
            }
        });
        Consulta.add(ConsultaGeral);

        alunoDados.add(Consulta);

        jMenuBar1.add(alunoDados);

        armarioDados.setText("Armarios");

        InserirArmario.setText("Inserir");
        InserirArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirArmarioActionPerformed(evt);
            }
        });
        armarioDados.add(InserirArmario);

        AlterarArmario.setText("Inserir");
        AlterarArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarArmarioActionPerformed(evt);
            }
        });
        armarioDados.add(AlterarArmario);

        ExlcuirArmario.setText("Inserir");
        ExlcuirArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExlcuirArmarioActionPerformed(evt);
            }
        });
        armarioDados.add(ExlcuirArmario);
        armarioDados.add(jSeparator2);

        ConsultarArmario.setText("Inserir");
        ConsultarArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarArmarioActionPerformed(evt);
            }
        });
        armarioDados.add(ConsultarArmario);

        jMenuBar1.add(armarioDados);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InserirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirAlunoActionPerformed
        
    }//GEN-LAST:event_InserirAlunoActionPerformed

    private void AlterarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarAlunoActionPerformed

    private void ConsultaPorAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPorAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaPorAlunoActionPerformed

    private void ConsultaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaGeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaGeralActionPerformed

    private void InserirArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirArmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirArmarioActionPerformed

    private void AlterarArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarArmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarArmarioActionPerformed

    private void ExlcuirArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExlcuirArmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExlcuirArmarioActionPerformed

    private void ConsultarArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarArmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarArmarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlterarAluno;
    private javax.swing.JMenuItem AlterarArmario;
    private javax.swing.JMenu Consulta;
    private javax.swing.JMenuItem ConsultaGeral;
    private javax.swing.JMenuItem ConsultaPorAluno;
    private javax.swing.JMenuItem ConsultarArmario;
    private javax.swing.JMenuItem ExcluirAluno;
    private javax.swing.JMenuItem ExlcuirArmario;
    private javax.swing.JMenuItem InserirAluno;
    private javax.swing.JMenuItem InserirArmario;
    private javax.swing.JMenu alunoDados;
    private javax.swing.JMenu armarioDados;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
